### ISSUE TITLE
Implement resolving types accross multiple XMI documents using the href attribute

### ISSUE THREAD

**Issue by samatstariongroup** [STARIONGROUP/uml4net#54]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the uml4net
- [x] I have searched [open](https://github.com/STARIONGROUP/uml4net/issues) and [closed](https://github.com/STARIONGROUP/uml4net/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
XMI allows a model to be described accros multiple XMI documents. According to the XMI standard there are multiple ways (using XML attributes) to reference types within 1 document and across documents with linking attributes
  - **idref** attribute: used to reference an XML element in the same document. The value of this attribute should be the value of the id attribute of the XML element. This uses the xsd:IDREF type, meaning it points to an element with an xsd:ID.
  - **type** attribute: The type attribute is used to specify the type of object being serialized, when the type is not known from the model. This can occur if the type of a reference has subclasses and the type cannot be determined (see ownedAttribute, this is already implemented). This means that not all XML elements will have a type attribute since the type can sometimes be determined from the model. I think a good example of this is the `<uml:Model>` element
  - **href** attribute: used to reference an XML element in the same document OR used to reference an XML element in another document. The value of the href attribute can take multiple forms:
    - href="other_model.xmi#Person" -> points to the XML Element with id="Person" in the other_model.xmi file which is relative to the current xmi document, in this case meaning in the same folder
    - href="http://example.com/models/another_model.xmi#Department" -> points to the XML Element with id="Department" in an XMI model located in a remote location. Since i don't think we should fetch it from the remote location we need to transform this to a relative pointer using an internal mechanism
    - href="#Email" -> points to the XML Element with id="Email" in the same document, this is effectively the same as using idref="Email"
    - href="pathmap://UML_PROFILES/UML.profile.uml#_0" -> the pathmap scheme or protocal is a logical scheme used to reference resources like models, libraries, and profiles, abstracting the physical file locations. Commonly used in modeling tools such as UML editor

> please note that the `#` can be used to point to XML Elements in the same file, see ` href="#Email"`, meaning that the current assembler in the PR is not correct. Please merge that in and we fix it later.

href can support multiple schemes such as http, https:, pathmap, file, platform, relative path
  - http and https: Used for referencing resources over the web. Typical for linking to online resources, such as UML profiles or libraries hosted on remote server
  - file: Used for referencing local files in a file system
  - platform: Commonly used in Eclipse-based modeling environments (like Papyrus). Refers to resources within an Eclipse workspace, making it easy to reference files without hardcoding full file paths
  - pathmap: A logical scheme used to reference resources like models, libraries, and profiles, abstracting the physical file locations. Commonly used in modeling tools such as UML editors.
  - relative path: Sometimes, XMI files simply use a relative file path to reference other models or resources, especially within the same project or folder structure

I propose that before we start with the assembler, we first check all the reference properties in the `SingleValueReferencePropertyIdentifiers` and `MultiValueReferencePropertyIdentifiers`. if we find any references that cannot be resolved from the current XMI file, then we load all the others untill we have all objects in the cache. Once that is done, the synchronize methdod should be able to resolve everything.

This will be recursive, meaning that if XMI model A depends on B and B depends on C and C depends on D; documents A, B, C and D will all need to be read prior to the assembler being able to resolve everything.

**Comment by nathanatstariongroup** [comment]
Closed in 8d0a0774c80411a9d5213d3f7f582f27a3c30e05 with [55](https://github.com/STARIONGROUP/uml4net/pull/55)
