### ISSUE TITLE
[Refactor] Assembler.TryGetReferencedElement - hack

### ISSUE THREAD

**Issue by samatstariongroup** [STARIONGROUP/uml4net#60]
@nathanatstariongroup I had to refactor the code below to make it work. This is a bit of a hack, can you clean this up?

https://github.com/STARIONGROUP/uml4net/blame/5b871f73ab4d483428cd69013a5c4f317568ab98/uml4net.xmireader/Cache/Assembler.cs#L127

**Comment by samatstariongroup** [comment]
@nathanatstariongroup can this be closed?

**Comment by nathanatstariongroup** [comment]
closed by #61
